/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  EventEmitter,
} from '@stencil/core';


export namespace Components {

  interface DatetimePicker {
    'selectedDate': Date;
  }
  interface DatetimePickerAttributes extends StencilHTMLAttributes {
    'onOnDateSelected'?: (event: CustomEvent<Date>) => void;
    'selectedDate'?: Date;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DatetimePicker': Components.DatetimePicker;
  }

  interface StencilIntrinsicElements {
    'datetime-picker': Components.DatetimePickerAttributes;
  }


  interface HTMLDatetimePickerElement extends Components.DatetimePicker, HTMLStencilElement {}
  var HTMLDatetimePickerElement: {
    prototype: HTMLDatetimePickerElement;
    new (): HTMLDatetimePickerElement;
  };

  interface HTMLElementTagNameMap {
    'datetime-picker': HTMLDatetimePickerElement
  }

  interface ElementTagNameMap {
    'datetime-picker': HTMLDatetimePickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
